# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('category', models.CharField(max_length=80)),
                ('bouns', models.CharField(max_length=80)),
            ],
        ),
    ]
