# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalid', models.IntegerField()),
                ('teamid', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('bouns', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Wrong_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chal', models.CharField(max_length=80)),
                ('team', models.CharField(max_length=80)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('flag', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='challenges',
            name='flag',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
