# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181019_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='bouns',
            field=models.CharField(default='{"0":0.15,"1":0.1,"2":0.05}', max_length=80),
        ),
    ]
