# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181019_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='school',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
