# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_teams_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
            },
        ),
        migrations.AlterModelOptions(
            name='challenges',
            options={'verbose_name': 'Challenge', 'verbose_name_plural': 'Challenges'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='wrong_keys',
            options={'verbose_name': 'Wrong Key', 'verbose_name_plural': 'Wrong Keys'},
        ),
        migrations.RenameField(
            model_name='solves',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='wrong_keys',
            old_name='data',
            new_name='date',
        ),
    ]
