# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181021_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='show',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
