# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20181021_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solves',
            old_name='chalid',
            new_name='chal',
        ),
        migrations.RenameField(
            model_name='solves',
            old_name='teamid',
            new_name='team',
        ),
    ]
