# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Challenges')),
            ],
            options={
                'verbose_name': 'Hint',
                'verbose_name_plural': 'Hints',
            },
        ),
    ]
