# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20181026_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solves',
            options={'verbose_name': 'Solve', 'verbose_name_plural': 'Solves'},
        ),
        migrations.AddField(
            model_name='solves',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrong_keys',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=15),
            preserve_default=False,
        ),
    ]
